Feature/onboard page
Revup-vn/revup-flutter-app-consumer pull request #10
Opened 2022-06-30 05:14 UTC by cantgim

2022-07-01 01:02 UTC, tcmhoang requested changes
Xong anh chay lenh `make format` va `make analyze` de format va chinh sua lai 1 so coding convention dang gap phai nhe a

2022-07-01 01:02 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +        nextStyle: TextButton.styleFrom(primary: Colors.black),
Neu dung duoc anh co gang dung color ben theme nhe a. Anh co the reference ben revup_core package de biet ve theme. Vi minh co dark mode va light mode nen color nay ko the hard-coded the nay dc

2022-07-01 01:02 UTC, tcmhoang commented on lib/router/app_router.dart
> +import 'package:revup/test/test.dart';
Vi day minh dung o 1 app nen anh co gang dung relative import nhe a

2022-07-01 08:34 UTC, cantgim commented on lib/l10n/arb/app_en.arb
> +  "btnDoneText": "Done"
oke e, mà a nghĩ nên để thêm tên màn vào: Tên màn + Tên component (hoặc widgets) + Type

2022-07-01 08:44 UTC, tcmhoang commented on lib/l10n/arb/app_en.arb
> +  "btnDoneText": "Done"
Em nghi la ko can. Vi `next` o man nay cung la `next` cua man khac a :)

2022-07-03 04:53 UTC, cantgim commented on lib/onboarding/view/onboarding_page.dart
> +        body: '',
cái này nó bắt buộc e ạ

2022-07-04 04:17 UTC, tcmhoang requested changes

2022-07-04 04:17 UTC, tcmhoang commented on lib/router/app_router.dart
> +import 'package:revup/test/test.dart';
2 Import nay van chua phai la relative import. Em vua thay doi o branch main de mn check coding convention. Anh xem lai nhe

2022-07-04 04:17 UTC, tcmhoang commented on lib/l10n/arb/app_en.arb
> +  "btnDoneText": "Done"
Bo cai `btn` di anh :)

2022-07-04 04:17 UTC, tcmhoang commented on lib/l10n/arb/app_en.arb
> +  "btnDoneText": "Done"
Voi ca `Text` nua. Ai cung biet no la String ma

2022-07-04 04:17 UTC, tcmhoang commented on lib/l10n/arb/app_vi.arb
> +  "btnDoneText": "Xong"
Anh sua cai nay lai luon nhe

2022-07-04 04:17 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +      titleTextStyle: TextStyle(fontSize: 28.0, fontWeight: FontWeight.w700),
Cai nay anh vua chua sua lai ma anh :(

2022-07-04 04:17 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +    ];
Chua bo xuong build cai variable nay anh

2022-07-04 04:17 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +        next: Text(l10n.btnDoneText),
Chua sua thanh AutoSizeText

2022-07-04 04:17 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +        nextStyle: TextButton.styleFrom(primary: Colors.black),
`Theme.of(context).TextButton` anh oi

2022-07-04 04:17 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +          activeColor: Color(0xFFFCD04E),
Chua sua theo mau cua theme

2022-07-04 04:32 UTC, tcmhoang requested changes

2022-07-04 04:32 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +  }
Stateless Class ko phai method anh

2022-07-04 04:32 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +    TextStyle? textStyle,
Khong can truyen vao anh. Minh lay tu context luon

2022-07-04 04:32 UTC, tcmhoang commented on lib/router/app_router.dart
> +    AdaptiveRoute<void>(page: OnboardingPage, initial: true),
Nho sua lai khi commit nhe anh

2022-07-04 04:32 UTC, tcmhoang commented on lib/l10n/arb/app_en.arb
> +  "doneButtonLabel": "Done"
Bo `ButtonLabel` di anh nhe

2022-07-04 04:40 UTC, cantgim commented on lib/onboarding/view/onboarding_page.dart
> +  }
cái PageViewModel của package này nó lại k extends từ widgets ấy. Nên lúc anh return về k đc, wrap lại bằng scaffold hay container để return về cũng k đc í 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/45166076/177082641-a9f38a6e-5214-4270-a0a8-8dc3f9333007.png">

2022-07-04 04:41 UTC, cantgim commented on lib/l10n/arb/app_en.arb
> +  "doneButtonLabel": "Done"
Để thành "nextLabel" thôi à e?

2022-07-04 04:58 UTC, tcmhoang commented on lib/l10n/arb/app_en.arb
> +  "doneButtonLabel": "Done"
de `next` thoi anh. Lo co man sau ma dung cai `next` thi do phai define lai

2022-07-04 05:07 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +  }
The anh de lai cai ten nhu `_toOnboardModel` de em ko tuong nhu no la widget anh. 
Anh dung tu `_build` hay `_render` lam em cu tuong widget :sweat_smile:

2022-07-04 05:08 UTC, tcmhoang commented on lib/onboarding/view/onboarding_page.dart
> +    TextStyle? textStyle,
The cai nay anh ko phai sua anh nhe

2022-07-04 05:08 UTC, tcmhoang commented
@cantgim  anh xem co van de gi nua ko anh nhe

2022-07-04 06:59 UTC, cantgim commented
> @cantgim anh xem co van de gi nua ko anh nhe

a hết r

2022-07-04 08:42 UTC, tcmhoang approved these changes

2022-07-04 08:44 UTC, merged