Feature/account page states
Revup-vn/revup-flutter-app-consumer pull request #12
Opened 2022-07-03 10:09 UTC by namngoc231

2022-07-04 04:02 UTC, tcmhoang requested changes
Xong anh nho chay 
```
make format
make analyze
make coverage
``` 
de test coding convention va % coverage nhe anh
Dong thoi em thay anh chua viet widget test

2022-07-04 04:02 UTC, tcmhoang commented on lib/payment/widgets/payment_item.dart
> +  // ignore: lines_longer_than_80_chars
Khong ignore lint anh nhe

2022-07-04 04:02 UTC, tcmhoang commented on lib/payment/widgets/payment_item.dart
> +          ),
Dung style cua theme neu anh muon thay doi dung method `copyWith`

2022-07-04 04:02 UTC, tcmhoang commented on lib/payment/widgets/payment_item.dart
> +        onPressed: () {},
Them TODO de noi anh dinh lam gi luc nay.
Nen pass 1 function agrument vao day de call

2022-07-04 16:30 UTC, namngoc231 commented on lib/account/widgets/account_item.dart
> +}
Để thế file nó dài quá nên a tách riêng ra

2022-07-07 03:29 UTC, tcmhoang requested changes

2022-07-07 03:29 UTC, tcmhoang commented on lib/account/widgets/circle_avatar.dart
> +              //     .copyWith(color: Theme.of(context).colorScheme.onPrimary),
+1

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/view/home_page.dart
> +            },
Dung cached_network_image a

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/view/home_page.dart
> +              );
+1

2022-07-07 03:29 UTC, tcmhoang commented on lib/account/widgets/account_item.dart
> +        onPressed: () {}, // TODO(namngoc231): implement on press
Neu dung chung nen chuyen callback vao day a

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/widgets/repair_review_home_page.dart
> +                ),
Truyen Url de hien thi avatar a
` sizeIcon: 0,`  em nghi nen truyen vao boolean de hien thi cai icon them anh thoi a

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/widgets/repair_review_home_page.dart
> +                    'Quang Nghĩa',
Ko hardcoded data anh. Pass qua params

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/widgets/repair_review_home_page.dart
> +                  '${l10n.dayLabel}: 17/ 10/2022',
+1

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.dart
> +                  'assets/screens/vehicle_maintenance.svg',
Dung file da gen ra anh. Ko truyen path vao

2022-07-07 03:29 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.dart
> +                ),
+1

2022-07-07 03:29 UTC, tcmhoang commented on lib/payment/widgets/payment_item.dart
> +        onPressed: () {}, // TODO(namngoc231): implement payments
Nen truyen callback vi cai nay anh dung o nhieu elements

2022-07-07 03:29 UTC, tcmhoang commented on lib/profile/view/update_profile_page.dart
> +                    //style: const TextStyle(fontSize: 18, color: Colors.white),
+1

2022-07-07 03:29 UTC, tcmhoang commented on lib/router/app_router.dart
> +    //AdaptiveRoute<void>(page: OnboardingPage),
+1

2022-07-07 03:29 UTC, tcmhoang commented on pubspec.yaml
> +  flutter_swiper: ^1.1.6
Dung thi dung 1 cai thoi a

2022-07-07 09:56 UTC, tcmhoang commented on lib/account/widgets/account_item.dart
> +        onPressed: () {}, // TODO(namngoc231): implement on press
`VoidCallBack` anh. Neu anh return `void` con khong anh xem docs hoac tu define function definition cho minh a

2022-07-11 03:37 UTC, tcmhoang requested changes
Anh revert commit nay ve commit trc do roi moi day len nha anh. Anh day ca file configs firebase cua minh len roi

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/cubit/account_cubit.dart
> +// }
+1

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/cubit/account_state.dart
> +// }
+1

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/view/account_page.dart
> +        'https://cdn.pixabay.com/photo/2017/09/27/15/52/man-2792456_1280.jpg';
Truyen vao parameters a

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/view/account_page.dart
> +            ),
Thieu state loading

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/view/account_page.dart
> +          crossAxisAlignment: CrossAxisAlignment.start,
Thay vi de `start` minh co the de `center` de do lap lai center property o children widgets

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/view/account_page.dart
> +              clickCallback: () {},
Them Todo o day nhe anh

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/view/account_page.dart
> +              clickCallback: () {},
Anh dung cai gi o day vay anh :)) sao lai co hex o day vay :)

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/account_item.dart
> +  // ignore: lines_longer_than_80_chars
+1

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/account_item.dart
> +        onPressed: clickCallback, // TODO(namngoc231): implement on press
Cai nay duoc chuyen vao roi anh xoa cai comment di anh

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/account_item.dart
> +        onPressed: clickCallback, // TODO(namngoc231): implement on press
ten cua cb anh chi can de callback hoac cb thoi. chu de clickCallBack hoi vo nghia anh

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/default_avatar.dart
> +            userName[0].toUpperCase(),
Check truong hop empty anh nhe

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/default_avatar.dart
> +                .copyWith(color: Theme.of(context).colorScheme.onPrimary),
Chua chac textSize de ko null anh xem them fallbackTextStyle anh nhe

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/use_avatar.dart
> +
+1

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/use_avatar.dart
> +      backgroundImage: CachedNetworkImageProvider(urlImage),
Check xem co load dc ko da anh. Neu ma no loi ko render dc thi sao anh

2022-07-11 03:37 UTC, tcmhoang commented on lib/account/widgets/use_avatar.dart
> +          ),
cho nay lap lai code o ben `default_avatar.dart` ko biet anh co nham gi ko anh

2022-07-11 03:37 UTC, tcmhoang commented on lib/firebase_options.dart
> +// File generated by FlutterFire CLI.
!!!!!

2022-07-11 16:37 UTC, namngoc231 commented on lib/account/widgets/default_avatar.dart
> +                .copyWith(color: Theme.of(context).colorScheme.onPrimary),
Mỗi màn textSize  khác nhau nên a không biết để fallbackTextStyle  như nào cho hợp lý

2022-07-12 03:57 UTC, namngoc231 commented on lib/account/view/account_page.dart
> +              clickCallback: () {},
Cái icon Change Language a ko tìm thấy trong material nên lấy cái này

2022-07-21 12:53 UTC, tcmhoang requested changes

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/model/user_model.dart
> +}
Dung freezed de gen class ra nhe a

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/model/user_data.dart
> +}
method fake data nen de o bloc thoi ko can tack ra lam file rieng dau anh

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +    final user = users.first;
Lang nghe state o UI thoi anh. Con lai thay doi internal data => Call o bloc

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +        padding: const EdgeInsets.fromLTRB(16, 60, 16, 0),
Body ma padding ca 3 chieu nay co khi bi loi. Dung SafeArea nhe a

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +                      ),
Cai handle avatar nay anh nen de o 1 file rieng vi nhieu man se dung no

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +                          onPressed: () {},
them todo

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +                        ],
default theme bi sao ma anh overwritten lai vay a?

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/widgets/default_avatar.dart
> +                  .copyWith(color: Theme.of(context).colorScheme.onPrimary),
ko dung null accessor operator anh. Anh them fallback value ho em nhe

2022-07-21 12:53 UTC, tcmhoang commented on lib/account/widgets/loading_avatar.dart
> +        highlightColor: Colors.grey[100]!,
Cai nay cung the anh nhe - fallback value

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/model/provider_data.dart
> +  }
De ben bloc nhe a

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/model/provider_model.dart
> +}
+1 freezed

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/view/home_page.u.dart
> +        AccountRoute(),
Anh Route kieu gi de cho van co navbar ben duoi nhe anh. Anh implement tam vai route cho man ko the de 3 cai giong nhau  ntn dc anh

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/widgets/repair_review_home_page.u.dart
> +                  onRatingUpdate: (double value) {},
TODO

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.u.dart
> +                      onPressed: () {},
TODO

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.u.dart
> +                      onPressed: () {},
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.u.dart
> +                      onPressed: () {},
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/home/widgets/support_home_page_item.u.dart
> +                        .textTheme
Neu giong nhau thi tach component ra anh

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/cubit/update_profile_cubit.dart
> +    await Future.delayed(const Duration(seconds: 1), () {});
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/cubit/update_profile_cubit.dart
> +    await Future.delayed(const Duration(seconds: 1), () {});
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/cubit/update_profile_state.dart
> +}
Da private thi private het nha a

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                Positioned(
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                        onPressed: () {},
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                          .labelLarge!
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                      _formKey.currentState?.fields['fullName']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                      _formKey.currentState?.fields['email']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                        },
expression body nhe anh ko dung bloc neu chi co return

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                          );
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                      if (_formKey.currentState!.saveAndValidate()) {
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                      fit: BoxFit.fitWidth,
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                        onPressed: () {},
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                          .labelLarge!
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                      _formKey.currentState?.fields['email']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                      _formKey.currentState?.fields['fullName']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                      _formKey.currentState?.fields['phone']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                      _formKey.currentState?.fields['address']!.validate();
+1

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +              ),
Ko can validate onChange anh. Chi can validate khi submit. Neu anh can validate on Change. Co cai property o form builder. Chu em nhin thay anh lap code nhieu qua

2022-07-21 12:53 UTC, tcmhoang commented on lib/profile/widgets/update_profile_view.u.dart
> +                        final data = _formKey.currentState!.value;
+1

2022-07-26 08:45 UTC, tcmhoang requested changes
Huy test UI ho cai @wamynobe

2022-07-26 08:45 UTC, tcmhoang commented on lib/account/bloc/account_bloc.dart
> +  }
Cai nay em nghi la state lay duoc du lieu anh. Nhung ma neu ko lay dc thi sao anh

2022-07-26 08:45 UTC, tcmhoang commented on lib/account/bloc/account_bloc.dart
> +  }
Thieu empty, loading, error nhe a

2022-07-26 08:45 UTC, tcmhoang commented on lib/account/bloc/account_event.dart
> +  const factory AccountEvent.started() = Started;
_private nhe a

2022-07-26 08:45 UTC, tcmhoang commented on lib/account/bloc/account_bloc.dart
> +    on<Started>(_onStarted);
Co gang dung `.when` nhe anh

2022-07-26 08:45 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +      create: (_) => AccountBloc()..add(const AccountEvent.started()),
state co o ban dau roi ko can phai add the nay a

2022-07-26 08:45 UTC, tcmhoang commented on lib/home/widgets/home_body_page.u.dart
> +              const AccountEvent.started(),
ko can add state dau nhe a

2022-07-26 08:45 UTC, tcmhoang commented on lib/home/widgets/repair_review_home_page.u.dart
> +    const dayRepair = '17/10/2022';
Move sang bloc nhe a

2022-07-26 08:45 UTC, tcmhoang commented on lib/profile/view/signup6_page.u.dart
> +                          },
Ko dung null accessor anh. Luon phai co fallback value

2022-07-26 08:45 UTC, tcmhoang commented on lib/profile/view/update_profile_page.u.dart
> +            ),
+1

2022-07-26 08:45 UTC, tcmhoang commented on lib/profile/view/update_profile_view.u.dart
> +                            orElse: () => '',
KOcan formt dau a. Em se handle cho ca app luon

2022-07-26 11:32 UTC, namngoc231 commented on lib/account/view/account_page.u.dart
> +      create: (_) => AccountBloc()..add(const AccountEvent.started()),
Có nghĩa là mình bỏ phần nào chú nhỉ, a ko hiểu lắm

2022-07-26 11:47 UTC, namngoc231 commented on lib/profile/view/update_profile_view.u.dart
> +                            orElse: () => '',
Phần này là BlocSelector a test thử xem khi Submit nó có lấy được dữ liệu để in ra màn hình được không thôi.

2022-07-26 23:52 UTC, tcmhoang requested changes

2022-07-26 23:52 UTC, tcmhoang commented on lib/account/view/account_page.u.dart
> +      create: (_) => AccountBloc()..add(const AccountEvent.started()),
Anh chua bo ha anh

2022-07-27 10:27 UTC, merged