Feature/login initial
Revup-vn/revup-flutter-app-consumer pull request #15
Opened 2022-07-05 19:48 UTC by cantgim

widget test a chưa viết hết, mà e cứ review qua nhé 🔥

2022-07-06 10:43 UTC, tcmhoang requested changes

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_bloc.dart
> +}
Anh de y event nguoi ta thuong dat la `Noun + Verb` nhe a
Eg: `SignInWithPhoneNumberPressed` => `PhoneNumberSignIn`

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_bloc.dart
> +}
Em tuong `PhoneNumberChangedIsValid` vs `PhoneNumberChangedIsInvalid` la `flutter_form_builder` no bat roi a

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
Anh xem co gi sua lai event nhe.
Em thay chi can 
* Initial
* Loading
* Submit
* Error
* thirdPartyLoginSubmit
* thirdPartyLoginError

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_state.dart
> +      );
Day ko phai cach gen file == `freezed` a. Anh xem lai example cua e nhe

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_state.dart
> +      );
Anh gen kieu nay se ko dung duoc method `map` va `when`

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
Class duoc gen la private class a 
Eg: `SignInWithPhoneNumberPressed` => `_SignInWithPhoneNumberPressed`

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +
file nay tach ra file `_page` nhe a

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +}
File nay de file `_view`

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +                  previous.phoneNumber != current.phoneNumber,
`BlocConsumer` thoi anh :))

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +}
Dung tao method render widget nhe a

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +                            errorText: '',
Them error text de hien len anh nhe

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_page.dart
> +                    //recognizer: TapGestureRecognizer()..onTap = () => ,
+1

2022-07-06 10:43 UTC, tcmhoang commented on test/login/login_page_test.dart
> +  setUp(() {});
Ko co `setUp` thi anh xoa di nhe

2022-07-06 10:43 UTC, tcmhoang commented on lib/login/view/login_sso_item.dart
> +          ),
File nay de la gi anh.
Sao anh lai Wrap cai Material vs Center the anh

2022-07-06 13:12 UTC, cantgim commented on lib/login/view/login_sso_item.dart
> +          ),
a để render cái này nè 
![image](https://user-images.githubusercontent.com/45166076/177558324-77c6b0cf-b4d4-4d4a-8237-f371aa9c72e9.png)

2022-07-06 16:36 UTC, cantgim commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
> Anh xem co gi sua lai event nhe. Em thay chi can
> 
> * Initial
> * Loading
> * Submit
> * Error
> * thirdPartyLoginSubmit
> * thirdPartyLoginError

sửa lại event hay state e nhỉ?

2022-07-06 16:38 UTC, cantgim commented on lib/login/bloc/login_state.dart
> +      );
> Day ko phai cach gen file == `freezed` a. Anh xem lai example cua e nhe

ừa. thế e xem state giữ những data này được chưa?

2022-07-06 16:46 UTC, cantgim commented on lib/login/view/login_page.dart
> +                  previous.phoneNumber != current.phoneNumber,
> `BlocConsumer` thoi anh :))

nhưng hiện tại a k dùng đến cái listener ấy, thì có cần chuyển k?

2022-07-07 01:28 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
Cai nay la Event a

2022-07-07 02:05 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
Em nham :))

2022-07-07 02:09 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +      SignInWithPhoneNumberPressed;
Events:
* Start
* Submit

States:
* Initial
* Loading
* Failure
* Success

2022-07-07 07:44 UTC, tcmhoang requested changes
Thieu handle states khi loi vs khi loading anh.
Loading anh co the dung flash package co cai dialog loading

2022-07-07 07:44 UTC, tcmhoang commented on lib/login/bloc/login_bloc.dart
> +    on<_Submit>((event, emit) {}); // TODO(cantgim): implement submit event
Cai event nay anh de public di anh `_Start` trong so qua

2022-07-07 07:44 UTC, tcmhoang commented on lib/login/bloc/login_event.dart
> +  const factory LoginEvent.submit() = _Submit;
Minh co submit vs dien thoai vs login == google sign-in. Em thay no thieu thieu day anh

2022-07-07 07:44 UTC, tcmhoang commented on lib/login/bloc/login_state.dart
> +  const factory LoginState.success({required String phoneNumber}) = _Success;
Co the thieu properties. De em implement cai authentication roi anh pull main ve de implement nhe a

2022-07-07 07:44 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                        ),
Thay vi `BlocBuilder` anh co the dung `BlocSelector` de build cai widget nay a. Thay moi value ben ElevayedButton chu ko can phai x2 nhu the a

2022-07-07 09:01 UTC, cantgim commented on lib/login/view/login_view.dart
> +                        ),
a chưa hiểu lắm, nếu thế thì phải viết state kiểu này mới sửa dụng được chỗ `selector` của `BlocSelector` à?
<img width="744" alt="image" src="https://user-images.githubusercontent.com/45166076/177735202-589eea57-eff1-4b33-bd6e-0355cf7ed941.png">

2022-07-07 09:13 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                        ),
ko anh

2022-07-07 09:13 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                        ),
Khong can sua the

2022-07-07 09:13 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                        ),
Luc ma dung Selector

2022-07-07 09:14 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                        ),
anh de kieu tra ve `Event,State,Boolean`

2022-07-08 08:13 UTC, tcmhoang commented on lib/login/view/login_view.dart
> +                  // ),
:))

2022-07-12 01:47 UTC, merged