Feature/102 choose services
Revup-vn/revup-flutter-app-consumer pull request #32
Opened 2022-07-25 06:43 UTC by cantgim

e check dần để a sửa nhé

2022-07-26 08:30 UTC, tcmhoang requested changes
@wamynobe  test ho UI tao may ao vs do phan giai 3.4 inch nhe

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-product/view/choose_product_view.u.dart
> +                                subtitle: const AutoSizeText('Đơn giá: '),
i11n dau a :)

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-product/view/choose_product_view.u.dart
> +                                      products[index].productImageUrl ?? '',
Vung `IVector`thay vi `List` nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/bloc/choose_service_bloc.dart
> +    on<NewServiceRequested>(_onNewServiceRequested);
Dung when => chuyen tat ca class thanh private nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/bloc/choose_service_bloc.dart
> +  Future<void> _onNewServiceRequested(
`Future<Unit>` nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/bloc/choose_service_bloc.dart
> +  Future<void> _onStarted(
Unit

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/bloc/choose_service_event.dart
> +  }) = ServiceSelectChanged;
class gen chuyen sang private nhe a.
Anh @namngoc231  master phan nay roi a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/view/choose_service_page.dart
> +        ..add(
ko can add event started nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/view/choose_service_view.u.dart
> +                          const Center(child: CircularProgressIndicator()),
Adaptive

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/view/choose_service_view.u.dart
> +                      failure: () => const Text('Failed'),
I11n

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/view/choose_service_view.u.dart
> +                            );
Neu ma anh get Index thi anh nen dung `IVector` nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/choose-service/view/service_details_page.dart
> +                        serviceData.products![index].productImageUrl ?? '',
ko dung null operator nhe anh. Chuyen sang IVecor . Sau do co fallback case

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/bloc/new_service_bloc.dart
> +    on<Submitted>(_onSubmitted);
.when nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/bloc/new_service_bloc.dart
> +      emit(NewServiceState.choosePhotoSuccess(_image));
Check flile co existed ko nhe anh

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +  late File? _image;
late con File? nay nguy hiem qua anh. Anh co the dung `Optional`

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                                context.router.pop();
pop nen await nhe anh. Loi ko biet dau nhu @wamynobe  la e chet :)

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                                context.router.pop();
+1

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                          return SizedBox(
Render state han che dung `maybe` methods nhe anh.  Dung thi anh nghi ro la nhung state nao render giong nhau

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                              imageUrl: _image!.path,
!!!

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/widgets/service_avatar.dart
> +          // ignore: implicit_dynamic_parameter
+1 explicit de la dynamic nhe anh ko ignore lint. 
Anh @namngoc231  master cai nay roi nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                        '';
Null accessor ko nendung anh. nen dung null coalesce operaor nhe a

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/widgets/service_checkbox_tile.dart
> +              // ignore: implicit_dynamic_parameter
!

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/widgets/service_checkbox_tile.dart
> +        subtitle: const AutoSizeText('Đơn giá: '),
!!!

2022-07-26 08:30 UTC, tcmhoang commented on lib/service/widgets/service_checkbox_tile.dart
> +              isChecked = value!;
!

2022-07-26 11:25 UTC, cantgim commented on ios/Runner/vi.lproj/InfoPlist.strings
> +"NSPhotoLibraryUsageDescription"="Cho phép Revup truy cập ảnh của bạn";
tiếng anh ở thư mục en.lproj ấy e ạ

2022-07-26 11:25 UTC, cantgim commented on .gitignore
> +lib/configs/.mapbox
file a config mapbox mà

2022-07-26 23:50 UTC, tcmhoang requested changes

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/choose-service/view/service_details_page.dart
> +                        serviceData.products![index].productImageUrl ?? '',
Anh ma de fallback the nay co ma loi luon app anh. Url nen la 1 cai ah ko bao h mat

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/new-service/bloc/new_service_bloc.dart
> +        emit(NewServiceState.success(serviceData));
+ trang thai failure nua a

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +  late File? _image;
anh xem lai the nao. Da `late` roi thi ko nen nullable

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +  late File? _image;
khong thi xoa `late` a

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/new-service/view/new_service_request_view.u.dart
> +                              imageUrl: _image!.path,
:)) Sua di anh oyy

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/widgets/service_checkbox_tile.dart
> +              imageUrl: widget.serviceData.imageUrl ?? '',
Anh check ho e cac anh phai co fallback nhe. parse `''` vao url image the nay loi app khi ko load dc anh

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/widgets/service_checkbox_tile.dart
> +              imageUrl: widget.serviceData.imageUrl ?? '',
Cai nay minh bat loi khi ma no ko co anh ma anh. Co phai them loi vao dau

2022-07-26 23:50 UTC, tcmhoang commented on lib/service/choose-service/bloc/choose_service_bloc.dart
> +          }
Failure thi sao a

2022-07-27 00:53 UTC, cantgim commented on lib/service/widgets/service_checkbox_tile.dart
> +              imageUrl: widget.serviceData.imageUrl ?? '',
có r mà e nhỉ? nó là 2 cái này nè e, k thì mình có url của default image thì a thêm vào cũng đc
<img width="524" alt="image" src="https://user-images.githubusercontent.com/45166076/181137106-5df5c4dc-be53-4f25-9d49-4ade2a5bae79.png">

2022-07-27 09:00 UTC, merged